GET http://localhost:3000/subscribers

###

GET http://localhost:3000/subscribers/60ef260fe335d2429cc7bcdf

###

POST http://localhost:3000/subscribers
Content-Type: application/json

{
    "name": "Kimmo Koodari",
    "subscribedToChannel":  "Koodiopit"
}

###

DELETE http://localhost:3000/subscribers/60ef260fe335d2429cc7bcdf

###

PATCH http://localhost:3000/subscribers/60ef2624e335d2429cc7bce1
Content-Type: application/json

{
    "name": "Uus nimi"
}